db:
  name: wp-database
  labels:
    id: C0927678
    app: wordpress
    env: dev
  image:
    repository: mariadb
    tag: 10.6.4-focal
    pullPolicy: Always
  replicas: 2
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: "wordpress"
    MYSQL_USER: "c0929542"
    APP_ENV: dev
  containerPorts:
      mysql: 3306
